language: ruby 

rvm: 
  - 1.9.3
  - 2.0.0

before_script: 
  - psql -c 'create database open_camp_test' -U vagrant

# script: rake
#
# using default travis ci 'rake' command to execute test suite
# see this page for more info
# http://about.travis-ci.org/docs/user/languages/ruby/#Default-Test-Script

